server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080
spring:
  config:
    import: optional:aws-parameterstore:/config/tarotmate
  mail:
    host: smtp.naver.com
    port: 465
    username: ${mail-id}
    password: ${mail-pw}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
      mail.smtp.starttls.enable: true
  profiles:
    active: prod
