name: Build CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Gradle Build Action
      uses: gradle/gradle-build-action@v2.9.0
      with:
        # 필요한 경우 Gradle 버전 지정
        gradle-version: '8.4'
        # 빌드 루트 디렉토리 지정
        build-root-directory: 'tarot'
        # Gradle 빌드에 필요한 추가 인자 지정
        arguments: build
